### ISSUE TITLE
TELA DE GERENCIAMENTO DE ITENS DO CHECKLIST

### ISSUE THREAD

**Issue by aocastro** [aocastro/GerenciadorEventoEtec#20]
Desenvolvimento de tela gerencial para as funcionalidades do checklist padrão do sistema.

- [ ] Tela de listagem dos registros
- [ ] Tela para inserção de novos registro
- [ ] Tela para visualização de registro
- [ ] Tela para edição de registro

**PARA ESSA TABELA NÃO SE APLICA EXCLUSÃO**
